version: '3'

services:

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: toor
      MYSQL_DATABASE: my_portfolio
      MYSQL_USER: yassine
      MYSQL_PASSWORD: toor
    ports:
      - "3306:3306"
    volumes:
      - dbdata:/var/lib/mysql


volumes:
  dbdata: