vich_uploader:
    db_driver: orm

    #mappings:
    #    products:
    #        uri_prefix: /images/products
    #        upload_destination: '%kernel.project_dir%/public/images/products'
    #        namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
    mappings:
        portfolio_images:
            uri_prefix: '%portfolio_img%'
            upload_destination:   '%kernel.project_dir%/public/%portfolio_img%'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            delete_on_remove:     false
            delete_on_update:     false